# Generated by Django 4.1 on 2024-03-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estimate_items',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedebit1',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item_History',
        ),
        migrations.DeleteModel(
            name='ItemModel',
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
