# Generated by Django 4.1 on 2024-03-05 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0002_remove_itemmodel_company_remove_itemmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_hsn', models.PositiveIntegerField(null=True)),
                ('item_unit', models.CharField(max_length=255)),
                ('item_taxable', models.CharField(max_length=255)),
                ('item_gst', models.CharField(max_length=255, null=True)),
                ('item_igst', models.CharField(max_length=255, null=True)),
                ('item_sale_price', models.PositiveIntegerField()),
                ('item_purchase_price', models.PositiveBigIntegerField()),
                ('item_opening_stock', models.PositiveBigIntegerField(default=0)),
                ('item_current_stock', models.PositiveBigIntegerField(default=0)),
                ('item_at_price', models.PositiveBigIntegerField(default=0)),
                ('item_date', models.DateField()),
                ('item_min_stock_maintain', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_invoice', models.PositiveBigIntegerField(blank=True, null=True)),
                ('trans_user_name', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('trans_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_current_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_adjusted_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_price', models.PositiveBigIntegerField(default=0)),
                ('trans_status', models.CharField(max_length=255)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='deliverychallanitems',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='estimate_items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchasedebit1',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='sales_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
    ]
