# Generated by Django 4.1 on 2024-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0003_itemmodel_transactionmodel_item_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_at_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_current_stock',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_hsn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_min_stock_maintain',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_opening_stock',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_purchase_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_sale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_taxable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
