# Generated by Django 4.1 on 2024-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0023_auto_20231226_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
