# Generated by Django 4.1 on 2024-01-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0024_party_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='balance',
            new_name='current_balance',
        ),
    ]
