# Generated by Django 4.1 on 2024-01-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0026_partyhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartyHistory',
            new_name='party_history',
        ),
    ]
